### ISSUE TITLE
打包成jar后，怎么配置机器人信息

### ISSUE THREAD

**Issue by kukume** [simple-robot/simbot-component-onebot#125]
### 是否会提供贡献？

否

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 内容描述

打包成jar后，怎么配置机器人信息，尝试在jar同级目录放simbot-bots文件夹，无用

**Comment by ForteScarlet** [comment]
如果使用了spring，可以参考[文档](https://simbot.forte.love/spring-boot.html#%E5%8F%AF%E9%85%8D%E7%BD%AE%E9%A1%B9) 的 `simbot.bots.configuration-json-resources` 属性，自定义配置文件的扫描路径，比如：
```yml
simbot:
  bots:
    configuration-json-resources:
      - 'file:simbot-bots/*.bot.json'
```

因为默认是 `classpath:simbot-bots/*.bot.json`, 所以只会扫描jar内资源，可修改为 `file:` 前缀。

相关参考：[Spring: Resources](https://docs.spring.io/spring-framework/reference/core/resources.html#resources-resourceloader)
